-- used to create differnt role levels for data reveal

CREATE ROLE IF NOT EXISTS SENIOR_ANALYST;
CREATE ROLE IF NOT EXISTS ANALYST;
CREATE ROLE IF NOT EXISTS DATA_OWNER;

GRANT USAGE ON DATABASE PROD_DEMO_DB TO ROLE SENIOR_ANALYST;
GRANT USAGE ON SCHEMA PROD_DEMO_DB.PUBLIC TO ROLE SENIOR_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA PROD_DEMO_DB.PUBLIC TO ROLE SENIOR_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PROD_DEMO_DB.PUBLIC TO ROLE SENIOR_ANALYST;
GRANT USAGE ON WAREHOUSE PROD_DEMO_WH TO ROLE SENIOR_ANALYST;

GRANT USAGE ON DATABASE PROD_DEMO_DB TO ROLE ANALYST;
GRANT USAGE ON SCHEMA PROD_DEMO_DB.PUBLIC TO ROLE ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA PROD_DEMO_DB.PUBLIC TO ROLE ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PROD_DEMO_DB.PUBLIC TO ROLE ANALYST;
GRANT USAGE ON WAREHOUSE PROD_DEMO_WH TO ROLE ANALYST;

GRANT USAGE ON DATABASE PROD_DEMO_DB TO ROLE DATA_OWNER;
GRANT USAGE ON SCHEMA PROD_DEMO_DB.PUBLIC TO ROLE DATA_OWNER;
GRANT ALL ON ALL TABLES IN SCHEMA PROD_DEMO_DB.PUBLIC TO ROLE DATA_OWNER;
GRANT ALL ON FUTURE TABLES IN SCHEMA PROD_DEMO_DB.PUBLIC TO ROLE DATA_OWNER;
GRANT USAGE ON WAREHOUSE PROD_DEMO_WH TO ROLE DATA_OWNER;

---
GRANT APPLICATION ROLE VGS_VAULT_TOKENIZER.VGS_APP_PUBLIC TO ROLE ANALYST; 
GRANT APPLICATION ROLE VGS_VAULT_TOKENIZER.VGS_APP_PUBLIC TO ROLE DATA_OWNER; 
GRANT APPLICATION ROLE VGS_VAULT_TOKENIZER.VGS_APP_PUBLIC TO ROLE SENIOR_ANALYST; 
