-- Run as native_app_developer / admin that installed app for every role *after* the app is installed




-- for each level added in the Data Classificaiton page *after* it is created in the app

-- do this for every field once it is set to tokeinze in the app 
-- ALTER TAG VGS_VAULT_TOKENIZER.ADMIN.<NAME_IN_DATA_CLASS_TAB>_TAG SET MASKING POLICY VGS_VAULT_TOKENIZER.ADMIN.VGS_REVEAL_<NAME_IN_DATA_CLASS_TAB>_MASKING_POLICY;


ALTER TAG VGS_VAULT_TOKENIZER.ADMIN.RED_TAG SET MASKING POLICY VGS_VAULT_TOKENIZER.ADMIN.VGS_REVEAL_RED_MASKING_POLICY;
ALTER TAG VGS_VAULT_TOKENIZER.ADMIN.YELLOW_TAG SET MASKING POLICY VGS_VAULT_TOKENIZER.ADMIN.VGS_REVEAL_YELLOW_MASKING_POLICY;
ALTER TAG VGS_VAULT_TOKENIZER.ADMIN.GREEN_TAG SET MASKING POLICY VGS_VAULT_TOKENIZER.ADMIN.VGS_REVEAL_GREEN_MASKING_POLICY;

-- ALTER TABLE DEMO.PUBLIC.<table> MODIFY COLUMN <column_name> SET TAG VGS_VAULT_TOKENIZER.admin.<NAME_IN_DATA_CLASS_TAB>_TAG = '<NAME_IN_DATA_CLASS_TAB>'; <- this last doesnt need _tag
ALTER TABLE PROD_DEMO_DB.PUBLIC.ACCOUNT_SUMMARY_DATA MODIFY COLUMN Account_SSN SET TAG VGS_VAULT_TOKENIZER.admin.RED_TAG = 'RED';

ALTER TABLE PROD_DEMO_DB.PUBLIC.CUSTOMER_DATA MODIFY COLUMN first_name SET TAG VGS_VAULT_TOKENIZER.admin.YELLOW_TAG = 'YELLOW';
ALTER TABLE PROD_DEMO_DB.PUBLIC.CUSTOMER_DATA MODIFY COLUMN last_name SET TAG VGS_VAULT_TOKENIZER.admin.YELLOW_TAG = 'YELLOW';
ALTER TABLE PROD_DEMO_DB.PUBLIC.CUSTOMER_DATA MODIFY COLUMN email SET TAG VGS_VAULT_TOKENIZER.admin.YELLOW_TAG = 'YELLOW';

--ALTER TABLE PROD_DEMO_DB.PUBLIC.CUSTOMER_DATA MODIFY COLUMN ip_address set TAG VGS_VAULT_TOKENIZER.admin.YELLOW_TAG = 'YELLOW';

ALTER TABLE PROD_DEMO_DB.PUBLIC.CUSTOMER_DATA MODIFY COLUMN ssn_number SET TAG VGS_VAULT_TOKENIZER.admin.RED_TAG = 'RED';

ALTER TABLE PROD_DEMO_DB.PUBLIC.CUSTOMER_DATA MODIFY COLUMN drivers_lic SET TAG VGS_VAULT_TOKENIZER.admin.RED_TAG = 'RED';

ALTER TABLE PROD_DEMO_DB.PUBLIC.CUSTOMER_DATA MODIFY COLUMN pet_name SET TAG VGS_VAULT_TOKENIZER.admin.GREEN_TAG = 'GREEN';