CREATE DATABASE PROD_DEMO_DB;
USE DATABASE PROD_DEMO_DB;

CREATE WAREHOUSE PROD_DEMO_WH WITH 
  WAREHOUSE_TYPE =  STANDARD        --STANDARD | SNOWPARK-OPTIMIZED
  WAREHOUSE_SIZE =  XSMALL          -- XSMALL | SMALL | MEDIUM | LARGE | XLARGE | XXLARGE | XXXLARGE | X4LARGE | X5LARGE | X6LARGE
  MAX_CLUSTER_COUNT = 1
  MIN_CLUSTER_COUNT = 1
  SCALING_POLICY = ECONOMY          --STANDARD | ECONOMY
  AUTO_SUSPEND = NULL               --<num> | NULL
  AUTO_RESUME = TRUE                --TRUE | FALSE
  INITIALLY_SUSPENDED = FALSE
  ENABLE_QUERY_ACCELERATION = FALSE
  QUERY_ACCELERATION_MAX_SCALE_FACTOR = 8;


USE WAREHOUSE PROD_DEMO_WH;
