CREATE DATABASE DEMO2;
USE DATABASE DEMO2;

CREATE WAREHOUSE COMPUTE_WH WITH 
  WAREHOUSE_TYPE =  STANDARD        --STANDARD | SNOWPARK-OPTIMIZED
  WAREHOUSE_SIZE =  XSMALL          -- XSMALL | SMALL | MEDIUM | LARGE | XLARGE | XXLARGE | XXXLARGE | X4LARGE | X5LARGE | X6LARGE
  MAX_CLUSTER_COUNT = 1
  MIN_CLUSTER_COUNT = 1
  SCALING_POLICY = ECONOMY          --STANDARD | ECONOMY
  AUTO_SUSPEND = NULL               --<num> | NULL
  AUTO_RESUME = TRUE                --TRUE | FALSE
  INITIALLY_SUSPENDED = FALSE
  ENABLE_QUERY_ACCELERATION = FALSE
  QUERY_ACCELERATION_MAX_SCALE_FACTOR = 8;


USE WAREHOUSE COMPUTE_WH;

GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO APPLICATION VGS_TOKENIZER_PRIVATE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO APPLICATION VGS_TOKENIZER_PRIVATE;
GRANT MODIFY ON WAREHOUSE COMPUTE_WH TO APPLICATION VGS_TOKENIZER_PRIVATE;