-- used to create differnt role levels for data reveal

-- CREATE ROLE SENIOR_ANALYST;

-- CREATE ROLE ANALYST;

-- CREATE ROLE DATA_OWNER;

GRANT USAGE ON DATABASE DEMO2 TO ROLE SENIOR_ANALYST;
GRANT USAGE ON SCHEMA DEMO2.PUBLIC TO ROLE SENIOR_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA DEMO2.PUBLIC TO ROLE SENIOR_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DEMO2.PUBLIC TO ROLE SENIOR_ANALYST;
GRANT USAGE ON WAREHOUSE DEMO TO ROLE SENIOR_ANALYST;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SENIOR_ANALYST;

GRANT USAGE ON DATABASE DEMO2 TO ROLE ANALYST;
GRANT USAGE ON SCHEMA DEMO2.PUBLIC TO ROLE ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA DEMO2.PUBLIC TO ROLE ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DEMO2.PUBLIC TO ROLE ANALYST;
GRANT USAGE ON WAREHOUSE DEMO TO ROLE ANALYST;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ANALYST;

GRANT USAGE ON DATABASE DEMO2 TO ROLE DATA_OWNER;
GRANT USAGE ON SCHEMA DEMO2.PUBLIC TO ROLE DATA_OWNER;
GRANT ALL ON ALL TABLES IN SCHEMA DEMO2.PUBLIC TO ROLE DATA_OWNER;
GRANT ALL ON FUTURE TABLES IN SCHEMA DEMO2.PUBLIC TO ROLE DATA_OWNER;
GRANT USAGE ON WAREHOUSE DEMO TO ROLE DATA_OWNER;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DATA_OWNER;