-- Run as native_app_developer / admin that installed app for every role *after* the app is installed




-- for each level added in the Data Classificaiton page *after* it is created in the app

-- do this for every field once it is set to tokeinze in the app 
-- ALTER TAG VGS_VAULT_TOKENIZER_DEMO.ADMIN.<NAME_IN_DATA_CLASS_TAB>_TAG SET MASKING POLICY VGS_VAULT_TOKENIZER_DEMO.ADMIN.VGS_REVEAL_<NAME_IN_DATA_CLASS_TAB>_MASKING_POLICY;


ALTER TAG VGS_VAULT_TOKENIZER_DEMO.ADMIN.Level_1_TAG SET MASKING POLICY VGS_VAULT_TOKENIZER_DEMO.ADMIN.VGS_REVEAL_LEVEL_1_MASKING_POLICY;
ALTER TAG VGS_VAULT_TOKENIZER_DEMO.ADMIN.LEVEL_2_TAG SET MASKING POLICY VGS_VAULT_TOKENIZER_DEMO.ADMIN.VGS_REVEAL_LEVEL_2_MASKING_POLICY;
ALTER TAG VGS_VAULT_TOKENIZER_DEMO.ADMIN.LEVEL_3_TAG SET MASKING POLICY VGS_VAULT_TOKENIZER_DEMO.ADMIN.VGS_REVEAL_LEVEL_3_MASKING_POLICY;

-- ALTER TABLE DEMO.PUBLIC.<table> MODIFY COLUMN <column_name> SET TAG VGS_VAULT_TOKENIZER_DEMO.admin.<NAME_IN_DATA_CLASS_TAB>_TAG = '<NAME_IN_DATA_CLASS_TAB>'; <- this last doesnt need _tag
ALTER TABLE PROD_DEMO_DB.PUBLIC.FAKE_ACCOUNT_SUMMARY_DATA MODIFY COLUMN Account_SSN SET TAG VGS_VAULT_TOKENIZER_DEMO.admin.LEVEL_1_TAG = 'LEVEL_1';

ALTER TABLE PROD_DEMO_DB.PUBLIC.FAKE_CUSTOMER_DATA MODIFY COLUMN first_name SET TAG VGS_VAULT_TOKENIZER_DEMO.admin.LEVEL_2_TAG = 'LEVEL_2';
ALTER TABLE PROD_DEMO_DB.PUBLIC.FAKE_CUSTOMER_DATA MODIFY COLUMN last_name SET TAG VGS_VAULT_TOKENIZER_DEMO.admin.LEVEL_2_TAG = 'LEVEL_2';
ALTER TABLE PROD_DEMO_DB.PUBLIC.FAKE_CUSTOMER_DATA MODIFY COLUMN email SET TAG VGS_VAULT_TOKENIZER_DEMO.admin.LEVEL_2_TAG = 'LEVEL_2';

ALTER TABLE PROD_DEMO_DB.PUBLIC.FAKE_CUSTOMER_DATA MODIFY COLUMN ip_address SET TAG VGS_VAULT_TOKENIZER_DEMO.admin.LEVEL_2_TAG = 'LEVEL_2';

ALTER TABLE PROD_DEMO_DB.PUBLIC.FAKE_CUSTOMER_DATA MODIFY COLUMN ssn_number SET TAG VGS_VAULT_TOKENIZER_DEMO.admin.LEVEL_1_TAG = 'LEVEL_1';

ALTER TABLE PROD_DEMO_DB.PUBLIC.FAKE_CUSTOMER_DATA MODIFY COLUMN drivers_lic SET TAG VGS_VAULT_TOKENIZER_DEMO.admin.LEVEL_1_TAG = 'LEVEL_1';

ALTER TABLE PROD_DEMO_DB.PUBLIC.FAKE_CUSTOMER_DATA MODIFY COLUMN pet_name SET TAG VGS_VAULT_TOKENIZER_DEMO.admin.LEVEL_3_TAG = 'LEVEL_3';