-- Run as native_app_developer / admin that installed app for every role *after* the app is installed
GRANT APPLICATION ROLE VGS_VAULT_TOKENIZER_DEMO.VGS_APP_PUBLIC TO ROLE ANALYST; 
GRANT APPLICATION ROLE VGS_VAULT_TOKENIZER_DEMO.VGS_APP_PUBLIC TO ROLE DATA_OWNER; 
GRANT APPLICATION ROLE VGS_VAULT_TOKENIZER_DEMO.VGS_APP_PUBLIC TO ROLE SENIOR_ANALYST; 
GRANT APPLICATION ROLE VGS_VAULT_TOKENIZER_DEMO.VGS_APP_PUBLIC TO ROLE ACCOUNTADMIN;

-- for each level added in the Data Classificaiton page *after* it is created in the app
-- ALTER TAG VGS_VAULT_TOKENIZER_DEMO.ADMIN.<NAME_IN_DATA_CLASS_TAB>_TAG SET MASKING POLICY VGS_VAULT_TOKENIZER_DEMO.ADMIN.VGS_REVEAL_<NAME_IN_DATA_CLASS_TAB>_MASKING_POLICY;


ALTER TAG VGS_VAULT_TOKENIZER_DEMO.ADMIN.Level_1_TAG SET MASKING POLICY VGS_VAULT_TOKENIZER_DEMO.ADMIN.VGS_REVEAL_LEVEL_1_MASKING_POLICY;
ALTER TAG VGS_VAULT_TOKENIZER_DEMO.ADMIN.LEVEL_2_TAG SET MASKING POLICY VGS_VAULT_TOKENIZER_DEMO.ADMIN.VGS_REVEAL_LEVEL_2_MASKING_POLICY;
ALTER TAG VGS_VAULT_TOKENIZER_DEMO.ADMIN.LEVEL_3_TAG SET MASKING POLICY VGS_VAULT_TOKENIZER_DEMO.ADMIN.VGS_REVEAL_LEVEL_3_MASKING_POLICY;

-- do this for every field once it is set to tokeinze in the app 
-- ALTER TABLE DEMO.PUBLIC.<table> MODIFY COLUMN <column_name> SET TAG VGS_VAULT_TOKENIZER_DEMO.admin.<NAME_IN_DATA_CLASS_TAB>_TAG = '<NAME_IN_DATA_CLASS_TAB>'; <- this last doesnt need _tag
ALTER TABLE DEMO.PUBLIC.VGS_SAMPLE_DATA MODIFY COLUMN FIRST_NAME SET TAG VGS_VAULT_TOKENIZER_DEMO.admin.LEVEL_1_TAG = 'LEVEL_1';