
GRANT USAGE ON INTEGRATION VGS_APP_INTEGRATION to application VGS_TOK_2;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO APPLICATION VGS_TOK_2; -- No need to change this one

-- These two, we have to change the database name
GRANT USAGE ON DATABASE DEMO2 TO APPLICATION VGS_TOK_2;
GRANT MODIFY ON DATABASE DEMO2 TO APPLICATION VGS_TOK_2;

-- These two, we have to change the schema name
GRANT USAGE ON SCHEMA DEMO2.PUBLIC TO APPLICATION VGS_TOK_2;
GRANT MODIFY ON SCHEMA DEMO2.PUBLIC TO APPLICATION VGS_TOK_2;

-- We need a warehouse to exist and all permissions on them to use tasks.
-- CREATE WAREHOUSE COMPUTE_WH;
GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO APPLICATION VGS_TOK_2;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO APPLICATION VGS_TOK_2;
GRANT MODIFY ON WAREHOUSE COMPUTE_WH TO APPLICATION VGS_TOK_2;

GRANT EXECUTE TASK ON ACCOUNT TO APPLICATION VGS_TOK_2;

-- Table grants, we need to change the name of the table

GRANT ALL PRIVILEGES ON TABLE DEMO2.PUBLIC.FAKE_ACCOUNT_SUMMARY_DATA TO APPLICATION VGS_TOK_2;
GRANT ALL PRIVILEGES ON TABLE DEMO2.PUBLIC.FAKE_CUSTOMER_DATA TO APPLICATION VGS_TOK_2;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN schema DEMO2.PUBLIC
TO APPLICATION VGS_TOK_2;

ALTER TABLE DEMO2.PUBLIC.FAKE_ACCOUNT_SUMMARY_DATA SET CHANGE_TRACKING = TRUE;

ALTER TABLE DEMO2.PUBLIC.FAKE_CUSTOMER_DATA SET CHANGE_TRACKING = TRUE;





