

CREATE WAREHOUSE IF NOT EXISTS PROD_DEMO_WH WITH 
  WAREHOUSE_TYPE =  STANDARD        --STANDARD | SNOWPARK-OPTIMIZED
  WAREHOUSE_SIZE =  XSMALL          -- XSMALL | SMALL | MEDIUM | LARGE | XLARGE | XXLARGE | XXXLARGE | X4LARGE | X5LARGE | X6LARGE
  MAX_CLUSTER_COUNT = 1
  MIN_CLUSTER_COUNT = 1
  SCALING_POLICY = ECONOMY          --STANDARD | ECONOMY
  AUTO_SUSPEND = NULL               --<num> | NULL
  AUTO_RESUME = TRUE                --TRUE | FALSE
  INITIALLY_SUSPENDED = FALSE
  ENABLE_QUERY_ACCELERATION = FALSE
  QUERY_ACCELERATION_MAX_SCALE_FACTOR = 8;


USE WAREHOUSE PROD_DEMO_WH;


CREATE OR REPLACE API INTEGRATION vgs_app_integration
  api_provider = aws_private_api_gateway
  api_aws_role_arn = 'arn:aws:iam::293664699268:role/snowflake-private'
  api_allowed_prefixes = ('https://ys8ux7iwbg.execute-api.us-west-2.amazonaws.com/snowflake/')
  enabled = true;

DESCRIBE API INTEGRATION vgs_app_integration;

SELECT SYSTEM$GET_SNOWFLAKE_PLATFORM_INFO();
Show integrations;

-- install app then grant access to interation and 

GRANT USAGE ON INTEGRATION VGS_APP_INTEGRATION to application VGS_VAULT_TOKENIZER;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO APPLICATION VGS_VAULT_TOKENIZER; 

GRANT OPERATE ON WAREHOUSE PROD_DEMO_WH TO APPLICATION VGS_VAULT_TOKENIZER;
-- REVOKE OPERATE ON WAREHOUSE PROD_DEMO_WH TO APPLICAITON VGS_VAULT_TOKENIZER; APP WILL NOT START - IT WIL HANG
GRANT USAGE ON WAREHOUSE PROD_DEMO_WH TO APPLICATION VGS_VAULT_TOKENIZER;
-- REVOKE USAGE ON WAREHOUSE PROD_DEMO_WH TO APPLICATION VGS_VAULT_TOKENIZER;
GRANT MODIFY ON WAREHOUSE PROD_DEMO_WH TO APPLICATION VGS_VAULT_TOKENIZER;

GRANT EXECUTE TASK ON ACCOUNT TO APPLICATION VGS_VAULT_TOKENIZER;
--REVOKE EXECUTE TASK ON ACCOUNT FROM APPLICATION VGS_VAULT_TOKENIZER;
