GRANT USAGE ON DATABASE INTAKE_STAGE_DB TO APPLICATION VGS_VAULT_TOKENIZER;
GRANT MODIFY ON DATABASE INTAKE_STAGE_DB TO APPLICATION VGS_VAULT_TOKENIZER;

-- These two, we have to change the schema name
GRANT USAGE ON SCHEMA INTAKE_STAGE_DB.PUBLIC TO APPLICATION VGS_VAULT_TOKENIZER;
GRANT MODIFY ON SCHEMA INTAKE_STAGE_DB.PUBLIC TO APPLICATION VGS_VAULT_TOKENIZER;

GRANT ALL PRIVILEGES ON TABLE INTAKE_STAGE_DB.PUBLIC.CUSTOMER_DATA TO APPLICATION VGS_VAULT_TOKENIZER;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN schema INTAKE_STAGE_DB.PUBLIC
TO APPLICATION VGS_VAULT_TOKENIZER;



ALTER TABLE INTAKE_STAGE_DB.PUBLIC.CUSTOMER_DATA SET CHANGE_TRACKING = TRUE;

GRANT USAGE ON DATABASE TARGET_DB TO APPLICATION VGS_VAULT_TOKENIZER;
--REVOKE USAGE ON DATABASE TARGET_DB FROM APPLICATION VGS_VAULT_TOKENIZER;


GRANT MODIFY ON DATABASE TARGET_DB TO APPLICATION VGS_VAULT_TOKENIZER;
--REVOKE MODIFY ON DATABASE TARGET_DB FROM APPLICATION VGS_VAULT_TOKENIZER;

-- These two, we have to change the schema name
GRANT USAGE ON SCHEMA TARGET_DB.ADMIN TO APPLICATION VGS_VAULT_TOKENIZER;
-- REVOKE USAGE ON SCHEMA TARGET_DB.ADMIN FROM APPLICATION VGS_VAULT_TOKENIZER;
GRANT MODIFY ON SCHEMA TARGET_DB.ADMIN TO APPLICATION VGS_VAULT_TOKENIZER;
-- REVOKE MODIFY ON SCHEMA TARGET_DB.ADMIN FROM APPLICATION VGS_VAULT_TOKENIZER;

GRANT ALL PRIVILEGES ON TABLE TARGET_DB.ADMIN.CUSTOMER_DATA TO APPLICATION VGS_VAULT_TOKENIZER;
-- REVOKE ALL PRIVILEGES ON TABLE TARGET_DB.ADMIN.CUSTOMER_DATA FROM APPLICATION VGS_VAULT_TOKENIZER;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN schema TARGET_DB.ADMIN
TO APPLICATION VGS_VAULT_TOKENIZER;



ALTER TABLE TARGET_DB.ADMIN.CUSTOMER_DATA SET CHANGE_TRACKING = FALSE;

ALTER TABLE INTAKE_STAGE_DB.PUBLIC.CUSTOMER_DATA SET CHANGE_TRACKING = TRUE;

GRANT USAGE ON DATABASE TARGET_DB TO APPLICATION VGS_VAULT_TOKENIZER;
GRANT MODIFY ON DATABASE TARGET_DB TO APPLICATION VGS_VAULT_TOKENIZER;

-- These two, we have to change the schema name
GRANT USAGE ON SCHEMA TARGET_DB.PUBLIC TO APPLICATION VGS_VAULT_TOKENIZER;
GRANT MODIFY ON SCHEMA TARGET_DB.PUBLIC TO APPLICATION VGS_VAULT_TOKENIZER;

GRANT ALL PRIVILEGES ON TABLE TARGET_DB.PUBLIC.CUSTOMER_DATA TO APPLICATION VGS_VAULT_TOKENIZER;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN schema TARGET_DB.PUBLIC
TO APPLICATION VGS_VAULT_TOKENIZER;



ALTER TABLE TARGET_DB.PUBLIC.CUSTOMER_DATA SET CHANGE_TRACKING = TRUE;