-- Run as native_app_developer / ADMIN that installed app for every role *after* the app is installed


-- for each level added in the Data Classificaiton page *after* it is created in the app

-- do this for every field once it is set to tokeinze in the app 
-- ALTER TAG VGS_VAULT_TOKENIZER.ADMIN.<NAME_IN_DATA_CLASS_TAB>_TAG SET MASKING POLICY VGS_VAULT_TOKENIZER.ADMIN.VGS_REVEAL_<NAME_IN_DATA_CLASS_TAB>_MASKING_POLICY;
SHOW MASKING POLICIES in vgs_vault_tokenizer.ADMIN;

-- masking policies for data owner rol and every data classificaion data owner has access to combo - MUST ALTER AT LEAST ONE TABLE FIRST WITH THE COMBO
ALTER TAG VGS_VAULT_TOKENIZER.ADMIN.RED_DATA_OWNER_TAG SET MASKING POLICY VGS_VAULT_TOKENIZER.ADMIN.VGS_REVEAL_RED_DATA_OWNER_MASKING_POLICY;
ALTER TAG VGS_VAULT_TOKENIZER.ADMIN.YELLOW_DATA_OWNER_TAG SET MASKING POLICY VGS_VAULT_TOKENIZER.ADMIN.VGS_REVEAL_YELLOW_DATA_OWNER_MASKING_POLICY;
ALTER TAG VGS_VAULT_TOKENIZER.ADMIN.GREEN_DATA_OWNER_TAG SET MASKING POLICY VGS_VAULT_TOKENIZER.ADMIN.VGS_REVEAL_GREEN_DATA_OWNER_MASKING_POLICY;

--- masking polices for senior analyst role and every data classification senior analyst has access to combo - MUST ALTER ATLEAST ONE TABLE ONCE WITH THE COMBO
ALTER TAG VGS_VAULT_TOKENIZER.ADMIN.YELLOW_SENIOR_ANALYST_TAG SET MASKING POLICY VGS_VAULT_TOKENIZER.ADMIN.VGS_REVEAL_YELLOW_SENIOR_ANALYST_MASKING_POLICY;
ALTER TAG VGS_VAULT_TOKENIZER.ADMIN.GREEN_SENIOR_ANALYST_TAG SET MASKING POLICY VGS_VAULT_TOKENIZER.ADMIN.VGS_REVEAL_GREEN_SENIOR_ANALYST_MASKING_POLICY;


ALTER TAG VGS_VAULT_TOKENIZER.ADMIN.GREEN_ANALYST_TAG SET MASKING POLICY VGS_VAULT_TOKENIZER.ADMIN.VGS_REVEAL_GREEN_ANALYST_MASKING_POLICY;


-- ALTER TABLE DEMO.PUBLIC.<table> MODIFY COLUMN <column_name> SET TAG VGS_VAULT_TOKENIZER.ADMIN.<NAME_IN_DATA_CLASS_TAB>_TAG = '<NAME_IN_DATA_CLASS_TAB>'; <- this last doesnt need _tag
ALTER TABLE PROD_DEMO_DB.PUBLIC.REAL_ACCOUNT_SUMMARY_DATA MODIFY COLUMN ACCOUNT_SSN SET TAG VGS_VAULT_TOKENIZER.ADMIN.RED_DATA_OWNER_TAG = 'RED_DATA_OWNER_TAG';

ALTER TABLE PROD_DEMO_DB.PUBLIC.REAL_CUSTOMER_DATA MODIFY COLUMN ssn_number SET TAG VGS_VAULT_TOKENIZER.ADMIN.RED_DATA_OWNER_TAG = 'RED_DATA_OWNER_TAG';
ALTER TABLE PROD_DEMO_DB.PUBLIC.REAL_CUSTOMER_DATA MODIFY COLUMN drivers_lic SET TAG VGS_VAULT_TOKENIZER.ADMIN.RED_DATA_OWNER_TAG = 'RED_DATA_OWNER_TAG';


ALTER TABLE PROD_DEMO_DB.PUBLIC.REAL_CUSTOMER_DATA MODIFY COLUMN first_name SET TAG VGS_VAULT_TOKENIZER.ADMIN.YELLOW_DATA_OWNER_TAG = 'YELLOW_DATA_OWNER_TAG';
ALTER TABLE PROD_DEMO_DB.PUBLIC.REAL_CUSTOMER_DATA MODIFY COLUMN last_name SET TAG VGS_VAULT_TOKENIZER.ADMIN.YELLOW_DATA_OWNER_TAG = 'YELLOW_DATA_OWNER_TAG';
ALTER TABLE PROD_DEMO_DB.PUBLIC.REAL_CUSTOMER_DATA MODIFY COLUMN email SET TAG VGS_VAULT_TOKENIZER.ADMIN.YELLOW_DATA_OWNER_TAG = 'YELLOW_DATA_OWNER_TAG';
ALTER TABLE PROD_DEMO_DB.PUBLIC.REAL_CUSTOMER_DATA MODIFY COLUMN first_name SET TAG VGS_VAULT_TOKENIZER.ADMIN.YELLOW_SENIOR_ANALYST_TAG = 'YELLOW_SENIOR_ANALYST_TAG';
ALTER TABLE PROD_DEMO_DB.PUBLIC.REAL_CUSTOMER_DATA MODIFY COLUMN last_name SET TAG VGS_VAULT_TOKENIZER.ADMIN.YELLOW_SENIOR_ANALYST_TAG = 'YELLOW_SENIOR_ANALYST_TAG';
ALTER TABLE PROD_DEMO_DB.PUBLIC.REAL_CUSTOMER_DATA MODIFY COLUMN email SET TAG VGS_VAULT_TOKENIZER.ADMIN.YELLOW_SENIOR_ANALYST_TAG = 'YELLOW_SENIOR_ANALYST_TAG';


ALTER TABLE PROD_DEMO_DB.PUBLIC.REAL_CUSTOMER_DATA MODIFY COLUMN  pet_name SET TAG VGS_VAULT_TOKENIZER.ADMIN.GREEN_DATA_OWNER_TAG = 'GREEN_DATA_OWNER_TAG';
ALTER TABLE PROD_DEMO_DB.PUBLIC.REAL_CUSTOMER_DATA MODIFY COLUMN  pet_name SET TAG VGS_VAULT_TOKENIZER.ADMIN.GREEN_SENIOR_ANALYST_TAG = 'GREEN_SENIOR_ANALYST_TAG';
ALTER TABLE PROD_DEMO_DB.PUBLIC.REAL_CUSTOMER_DATA MODIFY COLUMN  pet_name SET TAG VGS_VAULT_TOKENIZER.ADMIN.GREEN_ANALYST_TAG = 'GREEN_ANALYST_TAG';

